# This is a basic workflow that is manually triggered

name: Create New Release


on:
  release:
    types: [published]
    
  workflow_dispatch:
    inputs:
      override:
        description: 'Version Number'     
        required: true
        default: '0.0.0'
      tags:
        description: 'Manual'  

jobs:
  
  MakeNewRelease:
    runs-on: ubuntu-latest

    steps:      
    - name: Get version
      id: Version
      shell: pwsh
      run: |
        if ("${{github.ref}}".trim() -notmatch '^refs/tags/v(\d+\.\d+\.\d+)$') {
          $version = "::set-output name=RELEASE_NUMBER::${{ github.event.inputs.override }}"
          echo $version
          exit
        }
        else
        {
          $version = $matches[1]
          $version = "::set-output name=RELEASE_NUMBER::$($version)"
        }
        
        Write-Host $version
        
    - name: Display
      run: |
        echo "Override ${{ github.event.inputs.override }}!"
        echo "Value ${{ steps.Version.outputs.RELEASE_NUMBER }}!"

        
  # - name: Deploy to nuget
   #   run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_DEPLOY_KEY }} --source https://api.nuget.org/v3/index.json

