name: Main workflow

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Manual'  
      
jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1

    - id: keydb
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: TroyWalshProf/setup-dotnet

    - name: "Print result"
      run: |
        echo "id: ${{ steps.keydb.outputs.release}}"
        echo "name: ${{ steps.keydb.outputs.release }}"
        echo "tag_name: ${{ steps.keydb.outputs }}"
        
    - name: Lint with PSScriptAnalyzer
      shell: pwsh
      run: |
            $header = @{Authorization = 'Bearer ${{ secrets.GITHUB_TOKEN }}' }
            $endPoint = "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases"
            $info = Invoke-RestMethod -Uri $endPoint -Headers $header
            $info
            
            $version = $info.name[0].Trim("v")

            $test=@'
            {"id":1,"type":"Vsts","name":"Release","variables":{"MAQSVersion":{"isSecret":false,"value":"?????"}}}
            '@

            $test.Replace("?????", $version)
            #Invoke-RestMethod -Uri $endPoint -Headers 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'

