name: Main workflow

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: "call action"
      id: last_release
      uses: InsonusK/get-latest-release@v1.0.1
      with:
        myToken: ${{ github.token }}
        exclude_types: "release"
        view_top: 1
    - name: "Print result"
      run: |
        echo "id: ${{ steps.last_release.outputs.id }}"
        echo "name: ${{ steps.last_release.outputs.name }}"
        echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
        echo "created_at: ${{ steps.last_release.outputs.created_atd }}"
        echo "draft: ${{ steps.last_release.outputs.draft }}"
        echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set Node.js 12
      uses: actions/setup-node@v1
      with:
        version: 12.x
    - run: npm ci
    - run: npm run build
    - run: npm run format-check
    - run: npm test
    - name: Verify no unstaged changes
      if: runner.os != 'windows'
      run: __tests__/verify-no-unstaged-changes.sh

  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clear tool cache
        run: mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
      - name: Setup dotnet 3.0.100
        uses: ./
        with:
          dotnet-version: 3.0.100
      - name: Verify dotnet
        if: runner.os != 'windows'
        run: __tests__/verify-dotnet.sh 3.0.100
      - name: Verify dotnet (Windows)
        if: runner.os == 'windows'
        run: __tests__/verify-dotnet.ps1 3.0.100

  test-proxy:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/core/runtime-deps:3.0-bionic
      options: --dns 127.0.0.1
    services:
      squid-proxy:
        image: datadog/squid:latest
        ports:
          - 3128:3128
    env:
      https_proxy: http://squid-proxy:3128
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clear tool cache
        run: rm -rf $RUNNER_TOOL_CACHE/*
      - name: Setup dotnet 3.0.100
        uses: ./
        with:
          dotnet-version: 3.0.100
      - name: Verify dotnet
        run: __tests__/verify-dotnet.sh 3.0.100

  test-bypass-proxy:
    runs-on: ubuntu-latest
    env:
      https_proxy: http://no-such-proxy:3128
      no_proxy: github.com,dotnetcli.blob.core.windows.net,download.visualstudio.microsoft.com,api.nuget.org
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clear tool cache
        run: mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
      - name: Setup dotnet 3.0.100
        uses: ./
        with:
          dotnet-version: 3.0.100
      - name: Verify dotnet
        run: __tests__/verify-dotnet.sh 3.0.100
